on:
  push:
    branches: [master]
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
name: CI
jobs:
  lint:
    name: "Vala Lint"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: elementary/actions/vala-lint@main
      with:
        dir: .
        conf: .vala-lint.conf
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-45
      options: --privileged
    steps:
    - uses: actions/checkout@v4
    - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: io.github.alainm23.planify.Devel.flatpak
        manifest-path: build-aux/io.github.alainm23.planify.Devel.json
        cache-key: flatpak-builder-${{ github.sha }}
        repository-name: flathub-beta
        repository-url: https://flathub.org/beta-repo/flathub-beta.flatpakrepo # until GNOME 45
